import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ExtensionDataService } from '../../services/extension-data.service';
interface ExtensionCard {
  appId: string;
  packageId: string;
  title: string;
  description: string;
  icon: string;
  tags: string[];
  route: string;
}

@Component({
  selector: 'app-extensions-landing',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './extensions-landing.component.html',
  styleUrl: './extensions-landing.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class ExtensionsLandingComponent {
  private readonly extensionData = inject(ExtensionDataService);

  readonly extensions = signal<ExtensionCard[]>([
    {
      appId: '11486102-aa19-43d7-be0c-70aba7d9a51a',
      packageId: 'cyrena.api_references',
      title: 'API References',
      description: 'Gives Cyréna persistent technical memory by storing structured documents alongside your project. API References capture APIs, architecture rules, contracts, module behavior, and integration patterns — generated by the AI or authored manually. The agent reads these each session to reason beyond context window limits, keeping knowledge accurate as the project grows.',
      icon: 'bi-journal-text',
      tags: ['Memory', 'Documentation', 'Architecture'],
      route: '/extensions/cyrena.api_references'
    },
    {
      appId: '11486102-aa19-43d7-be0c-70aba7d9a51a',
      packageId: 'cyrena.dotnet',
      title: '.NET Development',
      description: 'Builds .NET projects and solutions with a strictly enforced structure. All supported project types share a common base layout (Attributes, Contracts, Extensions, Models, Services, Options) with per-type additions for Blazor (Components, wwwroot) and MVC (Controllers, Views, wwwroot). In solution mode, only supported project types are indexed — unsupported projects are ignored rather than blocked. Project and solution descriptor files (.csproj, .sln, .slnx) and JSON configuration files are read-only to the agent and will never be modified.',
      icon: 'bi-filetype-cs',
      tags: ['.NET', 'C#', 'Blazor', 'MVC', 'Solution'],
      route: '/extensions/cyrena.dotnet'
    },
    {
      appId: '11486102-aa19-43d7-be0c-70aba7d9a51a',
      packageId: 'cyrena.platformio',
      title: 'PlatformIO',
      description: 'Builds PlatformIO embedded firmware projects targeting Arduino and ESP-IDF frameworks, with strictly enforced structure. Writable surfaces are limited to src/ (implementation) and include/ (public headers) — platformio.ini, sdkconfig, and dependency metadata are read-only and will never be modified. The agent locks to a single active environment and queries it before making any architecture decisions, so board, framework, MCU, and memory constraints are always grounded in reality. Follows embedded-safe coding rules throughout: static allocation preferred, no dynamic memory, no recursion, no blocking delays, no desktop abstractions. Dependency changes are flagged to the user with explicit instructions rather than applied silently.',
      icon: 'bi-cpu',
      tags: ['Embedded', 'Arduino', 'ESP-IDF', 'Firmware'],
      route: '/extensions/cyrena.platformio'
    },
    {
      appId: '11486102-aa19-43d7-be0c-70aba7d9a51a',
      packageId: 'cyrena.arduino_ide',
      title: 'Arduino IDE',
      description: 'Builds Arduino IDE firmware projects with a strictly enforced flat sketch structure. Only .ino (entry point), .cpp (implementation), and .h (header) files are valid — no subdirectories. This mirrors Arduino IDE\'s own sketch model and keeps AI-generated firmware consistent and portable across devices.',
      icon: 'bi-motherboard',
      tags: ['Embedded', 'Arduino', 'Firmware', 'Sketch'],
      route: '/extensions/cyrena.arduino_ide'
    },
    {
      appId: '11486102-aa19-43d7-be0c-70aba7d9a51a',
      packageId: 'cyrena.developer',
      title: 'Coding Assistant',
      description: 'Foundation extension required by all coding extensions. Provides the core assistant mode that aggressively minimises context window usage each iteration, file I/O operations, sticky notes for persistent short-form memory, and access to the DevelopPlan so the agent always works from a structured project plan.',
      icon: 'bi-code-slash',
      tags: ['Coding', 'Foundation', 'File I/O', 'Memory'],
      route: '/extensions/cyrena.developer'
    },
    {
      appId: 'ead9f857-5111-4759-a1f9-c75361e0a347',
      packageId: 'cyrena.tavily',
      title: 'Tavily Web Search',
      description: 'Gives Cyréna assistants access to live web search via the Tavily API. Requires a Tavily API key.',
      icon: 'bi-search',
      tags: ['Web Search', 'API Integration'],
      route: '/extensions/cyrena.tavily'
    }
  ]);
}
