<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.4.4</Version>
    <Authors>Vaya Nova</Authors>
    <Description>Core models, interfaces &amp; services to develop extensions for Cyréna</Description>
    <PackageIcon>cyrena.png</PackageIcon>
    <Title>Cyréna Core</Title>
    <RepositoryUrl>https://github.com/Christo262/Cyrena_App</RepositoryUrl>
    <PackageProjectUrl>https://cyrena.dev</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\cyrena.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <Target Name="PostPack" AfterTargets="Pack">
    <ItemGroup>
      <NugetPackages Include="bin\Debug\$(PackageId).$(PackageVersion).nupkg" />
    </ItemGroup>

    <Copy SourceFiles="@(NugetPackages)" DestinationFolder="../../../sdk" SkipUnchangedFiles="true" />
  </Target>

</Project>
