<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cyrena</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.3.0</Version>
    <Authors>Vaya Nova</Authors>
    <Description>Key components and shared components</Description>
    <PackageIcon>cyrena.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Title>Cyréna Components</Title>
    <RepositoryUrl>https://github.com/Christo262/Cyrena_App</RepositoryUrl>
    <PackageProjectUrl>https://cyrena.dev</PackageProjectUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\cyrena.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\developer\Cyrena.Developer.Core\readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapBlazor" />
    <PackageReference Include="BootstrapBlazor.Html2Pdf" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="BlazorMonaco" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Cyrena.Core\Cyrena.Core.csproj" />
  </ItemGroup>

  <Target Name="PostPack" AfterTargets="Pack">
    <ItemGroup>
      <NugetPackages Include="bin\Debug\$(PackageId).$(PackageVersion).nupkg" />
    </ItemGroup>

    <Copy SourceFiles="@(NugetPackages)" DestinationFolder="../../../sdk" SkipUnchangedFiles="true" />
  </Target>

</Project>
