<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena.Dotnet</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cyrena.Coding.Core" />
  </ItemGroup>

</Project>
