<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena.Synthesis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cyrena.Extensa.Core" />
    <PackageReference Include="Cyrena.Persistence.Core" />
  </ItemGroup>

</Project>
