<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena.Extensa</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\install-readme.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Cyrena.Extensa.Core\Cyrena.Extensa.Core.csproj" />
  </ItemGroup>

</Project>
