<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Cyrena</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
    <PackageReference Include="BlazorMonaco" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Cyrena.Core\Cyrena.Core.csproj" />
    <ProjectReference Include="..\Cyrena.Components.Core\Cyrena.Components.Core.csproj" />
  </ItemGroup>

</Project>
