<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena.Developer</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="blazor-app-prompt.md" />
    <None Remove="class-library-prompt.md" />
    <None Remove="Resources\templates\blazor-layout.txt" />
    <None Remove="Resources\templates\blazor-page.txt" />
    <None Remove="Resources\templates\blazor-root.txt" />
    <None Remove="Resources\templates\blazor-shared.txt" />
    <None Remove="Resources\templates\contract.txt" />
    <None Remove="Resources\templates\controller.txt" />
    <None Remove="Resources\templates\extension.txt" />
    <None Remove="Resources\templates\model.txt" />
    <None Remove="Resources\templates\option.txt" />
    <None Remove="Resources\templates\razor-partial.txt" />
    <None Remove="Resources\templates\service.txt" />
    <None Remove="Resources\templates\view.txt" />
    <None Remove="dotnet-prompt.md" />
    <None Remove="mvc-app-prompt.md" />
    <None Remove="mvc-lib-prompt.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\blazor-lib-prompt.md" />
    <EmbeddedResource Include="Resources\blazor-app-prompt.md" />
    <EmbeddedResource Include="Resources\class-library-prompt.md" />
    <EmbeddedResource Include="Resources\templates\attribute.txt" />
    <EmbeddedResource Include="Resources\templates\blazor-layout.txt" />
    <EmbeddedResource Include="Resources\templates\blazor-page.txt" />
    <EmbeddedResource Include="Resources\templates\blazor-root.txt" />
    <EmbeddedResource Include="Resources\templates\blazor-shared.txt" />
    <EmbeddedResource Include="Resources\templates\contract.txt" />
    <EmbeddedResource Include="Resources\templates\controller.txt" />
    <EmbeddedResource Include="Resources\templates\extension.txt" />
    <EmbeddedResource Include="Resources\templates\model.txt" />
    <EmbeddedResource Include="Resources\templates\option.txt" />
    <EmbeddedResource Include="Resources\templates\razor-partial.txt" />
    <EmbeddedResource Include="Resources\templates\service.txt" />
    <EmbeddedResource Include="Resources\templates\view.txt" />
    <EmbeddedResource Include="Resources\dotnet-prompt.md" />
    <EmbeddedResource Include="Resources\mvc-app-prompt.md" />
    <EmbeddedResource Include="Resources\mvc-lib-prompt.md" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\components\Cyrena.Components\Cyrena.Components.csproj" />
    <ProjectReference Include="..\..\developer\Cyrena.Developer.Core\Cyrena.Developer.Core.csproj" />
    <ProjectReference Include="..\..\extensa\Cyrena.Extensa.Core\Cyrena.Extensa.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="scp -r bin\Debug\net10.0\ C:\Users\cilli\AppData\Local\.cyrena\extensions\cyrena.dotnet" />
  </Target>

</Project>
