<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebView.Wpf" />
    <PackageReference Include="BootstrapBlazor" />
    <PackageReference Include="PdfPig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\extensa\Cyrena.Extensa.Components\Cyrena.Extensa.Components.csproj" />
    <ProjectReference Include="..\extensa\Cyrena.Extensa.Runtime\Cyrena.Extensa.Runtime.csproj" />
    <ProjectReference Include="..\persistence\Cyrena.Persistence.File\Cyrena.Persistence.File.csproj" />
    <ProjectReference Include="..\runtime\Cyrena.Runtime.Ollama\Cyrena.Runtime.Ollama.csproj" />
    <ProjectReference Include="..\runtime\Cyrena.Runtime.OpenAI\Cyrena.Runtime.OpenAI.csproj" />
    <ProjectReference Include="..\runtime\Cyrena.Runtime\Cyrena.Runtime.csproj" />
  </ItemGroup>

</Project>
