<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Cyrena.Extensa</RootNamespace>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Version>0.6.0</Version>
    <Authors>Vaya Nova</Authors>
    <Description>Core models, interfaces &amp; services to develop extensions for Cyrena</Description>
    <PackageIcon>cyrena.png</PackageIcon>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
    <Title>Cyréna Extensa Core</Title>
    <RepositoryUrl>https://github.com/Christo262/Cyrena_App</RepositoryUrl>
    <PackageProjectUrl>https://cyrena.dev</PackageProjectUrl>
    <PackageLicenseFile>license.md</PackageLicenseFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\..\cyrena.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\..\license.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\core\Cyrena.Core\Cyrena.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <Target Name="PostPack" AfterTargets="Pack" Condition="'$(Configuration)' == 'Debug'">
    <ItemGroup>
      <NugetPackages Include="bin\Debug\$(PackageId).$(PackageVersion).nupkg" />
    </ItemGroup>

    <Copy SourceFiles="@(NugetPackages)" DestinationFolder="../../../sdk" SkipUnchangedFiles="true" />
  </Target>

</Project>
