{
  "Id": "d79f0716-f30b-4bae-964b-1935244de163",
  "Title": "IClientService – Client‑Management Service Interface",
  "Summary": "Defines the contract for CRUD operations on Client entities.",
  "Keywords": [
    "Client",
    "CRUD",
    "Service",
    "Contract",
    "BusinessLogic",
    "DependencyInjection"
  ],
  "Content": "IClientService – Client‑Management Service Interface\n\nSummary\nDefines the contract for CRUD operations on Client entities. All business logic for client handling resides in Services/ClientService.cs, which implements this interface. Pages and components interact with clients exclusively through this contract, ensuring a clean separation of concerns and enabling easy unit testing or future implementation swaps.\n\nKeywords\nClient, CRUD, Service, Contract, BusinessLogic, DependencyInjection\n\nContent\n```csharp\n// File: Contracts/IClientService.cs\nusing System.Collections.Generic;\nusing System.Threading.Tasks;\nusing SimpleBlazor.Models;\n\nnamespace SimpleBlazor.Contracts;\n\n/// <summary>\n/// Service contract for managing <see cref=\"Client\"/> entities.\n/// </summary>\npublic interface IClientService\n{\n    /// <summary>\n    /// Creates a new client record.\n    /// </summary>\n    /// <param name=\"client\">The client to add.</param>\n    /// <returns>A task representing the asynchronous operation.</returns>\n    Task AddAsync(Client client);\n\n    /// <summary>\n    /// Deletes a client by its unique identifier.\n    /// </summary>\n    /// <param name=\"id\">The GUID of the client to delete.</param>\n    /// <returns>A task representing the asynchronous operation.</returns>\n    Task DeleteAsync(Guid id);\n\n    /// <summary>\n    /// Retrieves all clients.\n    /// </summary>\n    /// <returns>A collection of <see cref=\"Client\"/> instances.</returns>\n    Task<IEnumerable<Client>> GetAllAsync();\n\n    /// <summary>\n    /// Retrieves a single client by its unique identifier.\n    /// </summary>\n    /// <param name=\"id\">The GUID of the client to retrieve.</param>\n    /// <returns>The matching <see cref=\"Client\"/> or <c>null</c> if not found.</returns>\n    Task<Client?> GetByIdAsync(Guid id);\n\n    /// <summary>\n    /// Updates an existing client record.\n    /// </summary>\n    /// <param name=\"client\">The client with updated values.</param>\n    /// <returns>A task representing the asynchronous operation.</returns>\n    Task UpdateAsync(Client client);\n}\n```\n\nImplementation Notes\n\n1. Service Implementation – Services/ClientService.cs implements IClientService and delegates persistence to IHttpService.\n2. Dependency Injection – IClientService is registered in Program.cs as a scoped service, enabling pages to inject it via constructor injection.\n3. Unit Testing – The interface allows mocking for unit tests of pages and components without touching the underlying HTTP layer.\n4. Future Extensibility – Adding new methods (e.g., search or pagination) requires only updating the interface and corresponding service implementation; consuming components remain unchanged if they use the existing methods.\n\nReferences\n- Services/ClientService.cs – concrete implementation.\n- Pages/Clients.razor & Pages/ClientEdit.razor – pages that consume the service.\n- Program.cs – DI registration.",
  "Link": null,
  "FilePath": null
}